apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: nginx
        name: nginx
        # command: ["/bin/bash", "-c"] # to simulate an error
        # args: ["sleep 5; exit 1"] # to simulate an error
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 7 # Because it waits for 5 seconds to simulate an error, picked 7s here
