apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-persist-vol-claim
  namespace: mealie-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
