#!/usr/bin/bash
# A practical example of 'for' loop and 'continue' keyword.
# Searches the current directory, detects hidden and normal files.

for file in .* *; do
	[[ "$file" == .* ]] && echo "Hidden file: $file" && continue
	[[ -f "$file" ]] || continue
	echo "Processing: $file" 
done
